const cyberTopicsByLocale = {
  en: [
    {
      id: "1",
      title: "Phishing Attacks 🎣",
      description:
        "Phishing attacks are one of the most common ways cybercriminals steal your personal data. Imagine getting an email that looks exactly like it came from your bank, asking you to 'verify your account' by clicking a link. That link actually takes you to a fake website designed to capture your login details. Always check if the email address is slightly misspelled (like support@bannk.com instead of support@bank.com). If an email creates panic, like saying 'your account will be blocked', pause and think before clicking. When in doubt, call the company directly using the number on their website — not the one in the email. Phishing can also happen via SMS ('smishing') or calls ('vishing'), so always stay alert and never share sensitive data casually.",
      uri:"https://imgs.search.brave.com/Y7-A2CqaPaUFHDdWmGcTrfdo7rnJ06bgoapp5q7jHwo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4t/aWNvbnMtcG5nLmZy/ZWVwaWsuY29tLzI1/Ni83Mjc1LzcyNzU4/MzgucG5nP3NlbXQ9/YWlzX2h5YnJpZA"
    },
    {
      id: "2",
      title: "Strong Passwords 🔑",
      description:
        "Using weak or repeated passwords is like leaving your front door unlocked. A strong password should be at least 12–16 characters, combining uppercase and lowercase letters, numbers, and symbols. For instance, 'MyDog$ammy2024!' is much better than 'password123'. Never reuse passwords across websites, because if one site gets hacked, attackers can try the same password elsewhere. To remember complex passwords, use a reputable password manager instead of writing them on paper or saving them in your notes app. Change your passwords every few months, and avoid obvious choices like your name, birthdate, or common words. Think of your password as your digital key — it should be unique and secret.",
      uri:"https://imgs.search.brave.com/jVqkTQuXeszui2oGR00JkmC9FgDvV4-iqa7Wm1Dn7Ec/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzExLzYwLzc4LzUw/LzM2MF9GXzExNjA3/ODUwMjNfVjBCbUtN/V2JidXlJc3VHRDhm/RndiaW1GYzRUVG54/dU8uanBn"
    },
    {
      id: "3",
      title: "Public Wi-Fi Risks 📶",
      description:
        "Free Wi-Fi at cafes, airports, or malls can be convenient but is often insecure. Hackers on the same network can easily intercept what you’re browsing or even inject malware into your device. For example, logging into your email on public Wi-Fi without protection could let someone steal your login details. Avoid accessing sensitive information, making payments, or downloading files when connected to public networks. If you must use it, use a trusted VPN app that encrypts your internet traffic, making it harder for others to spy on you. Also, always turn off sharing options and forget the network after use.",
      uri:"https://imgs.search.brave.com/KJHjzWqTq1rkVtxUGKl6UhVVIZ-CdcyPA8wKtO05jaY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/cHJlbWl1bS12ZWN0/b3IvcHVibGljLWZy/ZWUtd2lyZWxlc3Mt/Y29ubmVjdGlvbi1m/cmVlLXdpcmVsZXNz/LXNlcnZpY2VzLWZs/YXQtdmVjdG9yLWls/bHVzdHJhdGlvbi1k/ZXNpZ25fNTM4NjEw/LTE2NzEuanBnP3Nl/bXQ9YWlzX2h5YnJp/ZCZ3PTc0MA"
    },
    {
      id: "4",
      title: "Regular Updates 🛡️",
      description:
        "Outdated software often contains known security flaws that hackers actively exploit. Companies regularly release updates (patches) that fix these vulnerabilities. For instance, an old browser might have a flaw that lets attackers run malicious code just by visiting a webpage. By keeping your operating system, apps, antivirus, and even smart devices updated, you greatly reduce your risk. Enable auto-updates wherever possible so you don’t miss important patches. Remember: updates aren't just about new features — they're critical for your device’s security and your personal data’s safety.",
      uri:"https://imgs.search.brave.com/V8EF-q5C_V5kZ6d2APO2ji1nJR1Idj1TRrrrfQ7NtPo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTEz/NjE4Mjg2Mi92ZWN0/b3IvbmV3LXVwZGF0/ZS1iYW5uZXItdGVt/cGxhdGUtaXNvbGF0/ZWQtb24td2hpdGUt/YmFja2dyb3VuZC12/ZWN0b3ItaWxsdXN0/cmF0aW9uLWZvci1z/dG9yZS1vbmxpbmUu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PVJDazVhMFhtTXhs/UjJXMlhraXZvUUpo/RXVRdzAtd2dPaVp2/aTJWd0ZfQ009"
    },
    {
      id: "5",
      title: "Two-Factor Authentication (2FA) 🔒",
      description:
        "2FA adds a second step after entering your password, like an OTP sent via SMS or a code generated by an authenticator app. Even if hackers steal your password, they still need this second code to access your account. For example, if someone guesses your Facebook password but doesn’t have your phone, they can’t log in. Always enable 2FA on your email, banking apps, and social media accounts. Authenticator apps (like Google Authenticator) are safer than SMS, as SMS codes can sometimes be intercepted. Using 2FA is like adding a strong lock on top of your password.",
      uri:"https://imgs.search.brave.com/JNWjLZkMcsDFkg7UrCxSeK3fyyT-1KaKBTsyQSEHwM4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMjcv/NzY5LzAxOS9zbWFs/bC8yZmEtaWNvbi10/d28tZmFjdG9yLXZl/cmlmaWNhdGlvbi1i/eS1tb2JpbGUtcGhv/bmUtdmVjdG9yLmpw/Zw"
    },
    {
      id: "6",
      title: "Recognizing Scam Calls 📞",
      description:
        "Scammers often call pretending to be from banks, government offices, or tech support, creating urgency to make you act without thinking. For instance, they might say, 'Your account will be frozen unless you verify it now.' They may ask for your OTP, card PIN, or to install apps that give them remote access. Remember: no genuine bank or authority will ever ask for sensitive info over a call. If you get such calls, politely hang up and call back using the official number from your bank’s website or your card. Also, teach family members — especially elders and children — to be cautious of such calls.",
      uri:"https://imgs.search.brave.com/pFOLkNDUm3o-VZeg9gzCxCy6MxOqCv9DJB-mMymhRqA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTUw/MDc5NjA4NC92ZWN0/b3IvY2FydG9vbi1z/bWFydC1waG9uZS13/aXRoLWFsZXJ0LW5v/dGljZS1mbGF0LXNp/bXBsZS10cmVuZC1t/b2Rlcm4tbG9nb3R5/cGUtZ3JhcGhpYy1k/ZXNpZ24uanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPVVWc0Q0/YXFBejlsWVo1Mzh4/aXdfSlFGQnJXa2sy/M2IxaGM5UXE5Q2Yz/SUk9"
    },
  ],

  hi: [
    {
      id: "1",
      title: "फ़िशिंग हमले 🎣",
      description:
        "फ़िशिंग हमले सबसे सामान्य साइबर अपराधों में से एक हैं, जहाँ धोखेबाज़ विश्वसनीय संस्था जैसे बैंक या कंपनी के नाम पर ईमेल या SMS भेजते हैं। उदाहरण के लिए, आपको एक मेल मिल सकता है जो बिलकुल असली बैंक का दिखता है और कहता है, 'अपना अकाउंट वेरीफाई करें'। ऐसा लिंक असली वेबसाइट की तरह दिखता है लेकिन आपके डेटा को चुराने के लिए होता है। हमेशा भेजने वाले का ईमेल ध्यान से जाँचें — जैसे support@bank.com के बजाय support@bannk.com हो सकता है। डराने वाली भाषा जैसे 'आज ही वेरिफाई करें वरना अकाउंट बंद हो जाएगा' देखकर तुरंत क्लिक न करें। शक हो तो सीधे वेबसाइट पर जाकर लॉगिन करें या ऑफिशियल नंबर पर कॉल करें। फ़िशिंग सिर्फ ईमेल में नहीं, बल्कि SMS (smishing) और कॉल (vishing) से भी हो सकती है।",
      uri:"https://imgs.search.brave.com/Y7-A2CqaPaUFHDdWmGcTrfdo7rnJ06bgoapp5q7jHwo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4t/aWNvbnMtcG5nLmZy/ZWVwaWsuY29tLzI1/Ni83Mjc1LzcyNzU4/MzgucG5nP3NlbXQ9/YWlzX2h5YnJpZA"
    },
    {
      id: "2",
      title: "मजबूत पासवर्ड 🔑",
      description:
        "कमज़ोर या एक जैसे पासवर्ड रखना ऐसा है जैसे घर का दरवाज़ा खुला छोड़ना। मजबूत पासवर्ड में 12–16 अक्षर, बड़े-छोटे अक्षर, नंबर और स्पेशल कैरेक्टर हों। जैसे 'MyDog$ammy2024!' 'password123' से कहीं बेहतर है। हर वेबसाइट के लिए अलग पासवर्ड रखें, ताकि एक अकाउंट हैक होने पर दूसरे सुरक्षित रहें। पासवर्ड याद रखने के लिए नोटबुक या नोट्स ऐप में न लिखें, बल्कि पासवर्ड मैनेजर का इस्तेमाल करें। कुछ महीनों में पासवर्ड बदलें और अपना नाम, जन्मतिथि या कॉमन शब्द न रखें।",
      uri:"https://imgs.search.brave.com/jVqkTQuXeszui2oGR00JkmC9FgDvV4-iqa7Wm1Dn7Ec/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzExLzYwLzc4LzUw/LzM2MF9GXzExNjA3/ODUwMjNfVjBCbUtN/V2JidXlJc3VHRDhm/RndiaW1GYzRUVG54/dU8uanBn"
    },
    {
      id: "3",
      title: "पब्लिक वाई-फाई के खतरे 📶",
      description:
        "कैफ़े, एयरपोर्ट या मॉल की फ्री वाई-फाई बहुत सुविधाजनक लगती है लेकिन असुरक्षित होती है। हैकर उसी नेटवर्क पर रहकर आपके डेटा को चुरा सकते हैं। जैसे, पब्लिक वाई-फाई पर बैंक अकाउंट लॉगिन करना आपके लॉगिन डिटेल्स लीक कर सकता है। संवेदनशील जानकारी देखने या पेमेंट करने से बचें। ज़रूरी हो तो VPN का उपयोग करें, जिससे आपके डेटा का ट्रैफिक एन्क्रिप्ट हो जाता है। नेटवर्क इस्तेमाल के बाद 'forget' करना और फ़ाइल शेयरिंग ऑफ़ करना भी ज़रूरी है।",
      uri:"https://imgs.search.brave.com/KJHjzWqTq1rkVtxUGKl6UhVVIZ-CdcyPA8wKtO05jaY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/cHJlbWl1bS12ZWN0/b3IvcHVibGljLWZy/ZWUtd2lyZWxlc3Mt/Y29ubmVjdGlvbi1m/cmVlLXdpcmVsZXNz/LXNlcnZpY2VzLWZs/YXQtdmVjdG9yLWls/bHVzdHJhdGlvbi1k/ZXNpZ25fNTM4NjEw/LTE2NzEuanBnP3Nl/bXQ9YWlzX2h5YnJp/ZCZ3PTc0MA"
    },
    {
      id: "4",
      title: "नियमित अपडेट 🛡️",
      description:
        "पुराने सॉफ्टवेयर में सुरक्षा खामियाँ हो सकती हैं, जिन्हें हैकर जानते हैं और फायदा उठाते हैं। अपडेट उन कमियों को ठीक करते हैं। जैसे पुराने ब्राउज़र में एक बग हो सकता है जिससे सिर्फ लिंक खोलकर वायरस आ जाए। मोबाइल, कंप्यूटर, ऐप्स और एंटीवायरस को समय-समय पर अपडेट रखें। ऑटो-अपडेट चालू करें, ताकि अपडेट छूटे नहीं। याद रखें, अपडेट सिर्फ नए फीचर के लिए नहीं, आपकी सुरक्षा के लिए भी ज़रूरी हैं।",
      uri:"https://imgs.search.brave.com/V8EF-q5C_V5kZ6d2APO2ji1nJR1Idj1TRrrrfQ7NtPo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTEz/NjE4Mjg2Mi92ZWN0/b3IvbmV3LXVwZGF0/ZS1iYW5uZXItdGVt/cGxhdGUtaXNvbGF0/ZWQtb24td2hpdGUt/YmFja2dyb3VuZC12/ZWN0b3ItaWxsdXN0/cmF0aW9uLWZvci1z/dG9yZS1vbmxpbmUu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PVJDazVhMFhtTXhs/UjJXMlhraXZvUUpo/RXVRdzAtd2dPaVp2/aTJWd0ZfQ009"
    },
    {
      id: "5",
      title: "दो-चरणीय प्रमाणीकरण (2FA) 🔒",
      description:
        "2FA पासवर्ड के बाद एक और सुरक्षा परत है — जैसे SMS से आया OTP या Google Authenticator का कोड। मान लीजिए किसी को आपका पासवर्ड मिल भी जाए, तब भी OTP के बिना वो लॉगिन नहीं कर पाएगा। बैंक, सोशल मीडिया और ईमेल पर ज़रूर 2FA लगाएँ। SMS से OTP सुरक्षित होता है लेकिन Authenticator ऐप और भी बेहतर होते हैं, क्योंकि SMS इंटरसेप्ट किया जा सकता है।",
      uri:"https://imgs.search.brave.com/JNWjLZkMcsDFkg7UrCxSeK3fyyT-1KaKBTsyQSEHwM4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMjcv/NzY5LzAxOS9zbWFs/bC8yZmEtaWNvbi10/d28tZmFjdG9yLXZl/cmlmaWNhdGlvbi1i/eS1tb2JpbGUtcGhv/bmUtdmVjdG9yLmpw/Zw"
    },
    {
      id: "6",
      title: "फर्जी कॉल को पहचानें 📞",
      description:
        "अक्सर ठग बैंक या सरकारी कर्मचारी बनकर कॉल करते हैं और कहते हैं कि 'अभी पैसा ट्रांसफर करो वरना अकाउंट ब्लॉक होगा' या 'आपका कंप्यूटर वायरस से संक्रमित है'। वे OTP, कार्ड डिटेल या रिमोट ऐप इंस्टॉल करने के लिए कहते हैं। असली बैंक या संस्था कभी फोन पर ऐसी जानकारी नहीं माँगती। कॉल आते ही तुरंत काटें और ऑफिशियल नंबर से संपर्क करें। परिवार में बुजुर्ग और बच्चों को भी यह सावधानी सिखाएँ।",
      uri:"https://imgs.search.brave.com/pFOLkNDUm3o-VZeg9gzCxCy6MxOqCv9DJB-mMymhRqA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTUw/MDc5NjA4NC92ZWN0/b3IvY2FydG9vbi1z/bWFydC1waG9uZS13/aXRoLWFsZXJ0LW5v/dGljZS1mbGF0LXNp/bXBsZS10cmVuZC1t/b2Rlcm4tbG9nb3R5/cGUtZ3JhcGhpYy1k/ZXNpZ24uanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPVVWc0Q0/YXFBejlsWVo1Mzh4/aXdfSlFGQnJXa2sy/M2IxaGM5UXE5Q2Yz/SUk9"
    },
  ],

  pa: [
    {
      id: "1",
      title: "ਫਿਸ਼ਿੰਗ ਹਮਲੇ 🎣",
      description:
        "ਫਿਸ਼ਿੰਗ ਹਮਲਿਆਂ ਦੌਰਾਨ ਠੱਗ ਆਪਣੇ ਆਪ ਨੂੰ ਬੈਂਕ ਜਾਂ ਕਿਸੇ ਜਣੇ-ਪਛਾਣੇ ਸੰਸਥਾ ਵਜੋਂ ਦਰਸਾ ਕੇ ਤੁਹਾਡੀਆਂ ਜਾਨਕਾਰੀਆਂ ਚੁਰਾਉਂਦੇ ਹਨ। ਉਦਾਹਰਨ ਵਜੋਂ, ਬੈਂਕ ਦੇ ਨਾਂ 'ਤੇ ਈਮੇਲ ਆ ਸਕਦੀ ਹੈ ਜੋ ਤੁਹਾਨੂੰ 'ਖਾਤਾ ਵੈਰੀਫਾਈ' ਕਰਨ ਲਈ ਲਿੰਕ 'ਤੇ ਕਲਿਕ ਕਰਨ ਨੂੰ ਕਹੇਗੀ। ਉਹ ਲਿੰਕ ਅਸਲ ਵਿੱਚ ਨਕਲੀ ਵੈਬਸਾਈਟ ਹੁੰਦੀ ਹੈ। ਹਮੇਸ਼ਾਂ ਈਮੇਲ ਐਡਰੈੱਸ ਜਾਂ URL ਚੈੱਕ ਕਰੋ (ਜਿਵੇਂ support@bank.com ਦੇ ਬਦਲੇ support@bannk.com)। ਜੇ ਈਮੇਲ ਵਿਚ ਡਰਾਉਣੀ ਭਾਸ਼ਾ ਹੋਵੇ, ਜਿਵੇਂ 'ਤੁਰੰਤ ਕਰੋ ਨਹੀਂ ਤਾਂ ਖਾਤਾ ਬੰਦ ਹੋ ਜਾਏਗਾ', ਤਦ ਵੀ ਸੋਚ ਕੇ ਕਲਿਕ ਕਰੋ। ਕਦੇ ਵੀ ਸਿੱਧਾ ਲਿੰਕ 'ਤੇ ਨਾ ਕਲਿਕ ਕਰੋ, ਬੈਂਕ ਦੀ ਆਫੀਸ਼ਲ ਵੈਬਸਾਈਟ ਟਾਈਪ ਕਰਕੇ ਖੋਲ੍ਹੋ।",
      uri:"https://imgs.search.brave.com/Y7-A2CqaPaUFHDdWmGcTrfdo7rnJ06bgoapp5q7jHwo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4t/aWNvbnMtcG5nLmZy/ZWVwaWsuY29tLzI1/Ni83Mjc1LzcyNzU4/MzgucG5nP3NlbXQ9/YWlzX2h5YnJpZA"
    },
    {
      id: "2",
      title: "ਮਜ਼ਬੂਤ ਪਾਸਵਰਡ 🔑",
      description:
        "ਕਮਜ਼ੋਰ ਜਾਂ ਇੱਕੋ ਜਿਹਾ ਪਾਸਵਰਡ ਰੱਖਣ ਨਾਲ ਖਾਤਾ ਹੈਕ ਹੋ ਸਕਦਾ ਹੈ। ਪਾਸਵਰਡ ਘੱਟ ਤੋਂ ਘੱਟ 12 ਅੱਖਰ ਦਾ ਹੋਵੇ, ਵੱਡੇ-ਛੋਟੇ ਅੱਖਰ, ਨੰਬਰ ਅਤੇ ਸਿੰਬਲ ਸ਼ਾਮਲ ਹੋਣ। ਜਿਵੇਂ 'MyDog$ammy2024!' 'password123' ਨਾਲੋਂ ਕਈ ਗੁਣਾ ਬਿਹਤਰ ਹੈ। ਹਰ ਖਾਤੇ ਲਈ ਵੱਖਰਾ ਪਾਸਵਰਡ ਬਣਾਓ। ਪਾਸਵਰਡ ਯਾਦ ਰੱਖਣ ਲਈ ਨੋਟਬੁੱਕ ਜਾਂ ਮੋਬਾਈਲ ਨੋਟਸ ਵਿਚ ਨਾ ਲਿਖੋ, ਬਲਕਿ ਪਾਸਵਰਡ ਮੈਨੇਜਰ ਵਰਤੋਂ। ਕੁਝ ਮਹੀਨਿਆਂ ਵਿਚ ਪਾਸਵਰਡ ਬਦਲਦੇ ਰਹੋ।",
      uri:"https://imgs.search.brave.com/jVqkTQuXeszui2oGR00JkmC9FgDvV4-iqa7Wm1Dn7Ec/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzExLzYwLzc4LzUw/LzM2MF9GXzExNjA3/ODUwMjNfVjBCbUtN/V2JidXlJc3VHRDhm/RndiaW1GYzRUVG54/dU8uanBn"
    },
    {
      id: "3",
      title: "ਪਬਲਿਕ ਵਾਈ-ਫਾਈ ਦੇ ਖ਼ਤਰੇ 📶",
      description:
        "ਕੈਫੇ, ਏਅਰਪੋਰਟ ਜਾਂ ਮਾਲ ਦੀ ਮੁਫ਼ਤ ਵਾਈ-ਫਾਈ ਆਮ ਤੌਰ 'ਤੇ ਅਸੁਰੱਖਿਅਤ ਹੁੰਦੀ ਹੈ। ਹੈਕਰ ਉਹੀ ਨੈੱਟਵਰਕ ਵਰਤ ਕੇ ਤੁਹਾਡਾ ਡੇਟਾ ਲੈ ਸਕਦੇ ਹਨ। ਉਦਾਹਰਨ ਵਜੋਂ, ਜੇ ਤੁਸੀਂ ਪਬਲਿਕ ਵਾਈ-ਫਾਈ ਤੇ ਬੈਂਕ ਖਾਤਾ ਖੋਲ੍ਹਦੇ ਹੋ, ਕੋਈ ਤੁਹਾਡਾ ਲਾਗਿਨ ਚੁੱਕ ਸਕਦਾ ਹੈ। ਅਜਿਹੇ ਨੈੱਟਵਰਕ 'ਤੇ ਸੰਵੇਦਨਸ਼ੀਲ ਕੰਮ ਨਾ ਕਰੋ। ਜ਼ਰੂਰ ਹੋਵੇ ਤਾਂ VPN ਵਰਤੋਂ, ਜੋ ਤੁਹਾਡੀ ਟ੍ਰੈਫਿਕ ਨੂੰ ਇੰਕ੍ਰਿਪਟ ਕਰਦਾ ਹੈ।",
      uri:"https://imgs.search.brave.com/KJHjzWqTq1rkVtxUGKl6UhVVIZ-CdcyPA8wKtO05jaY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/cHJlbWl1bS12ZWN0/b3IvcHVibGljLWZy/ZWUtd2lyZWxlc3Mt/Y29ubmVjdGlvbi1m/cmVlLXdpcmVsZXNz/LXNlcnZpY2VzLWZs/YXQtdmVjdG9yLWls/bHVzdHJhdGlvbi1k/ZXNpZ25fNTM4NjEw/LTE2NzEuanBnP3Nl/bXQ9YWlzX2h5YnJp/ZCZ3PTc0MA"
    },
    {
      id: "4",
      title: "ਨਿਯਮਤ ਅੱਪਡੇਟ 🛡️",
      description:
        "ਪੁਰਾਣਾ ਸੌਫਟਵੇਅਰ ਹਮਲਿਆਂ ਲਈ ਖਾਮੀਆਂ ਰੱਖਦਾ ਹੈ। ਕੰਪਨੀਆਂ ਅੱਪਡੇਟ ਜਾਰੀ ਕਰਦੀਆਂ ਹਨ ਜੋ ਇਹ ਖਾਮੀਆਂ ਠੀਕ ਕਰਦੀਆਂ ਹਨ। ਜਿਵੇਂ ਪੁਰਾਣਾ ਬ੍ਰਾਊਜ਼ਰ ਖਤਰਨਾਕ ਕੋਡ ਚਲਾਉਣ ਲਈ ਹੈਕਰ ਵਰਤ ਸਕਦੇ ਹਨ। ਆਪਣੇ ਮੋਬਾਈਲ, ਕੰਪਿਊਟਰ, ਐਪਸ ਅਤੇ ਐਂਟੀਵਾਇਰਸ ਨੂੰ ਨਿਯਮਤ ਅੱਪਡੇਟ ਰੱਖੋ। ਆਟੋ-ਅੱਪਡੇਟ ਚਾਲੂ ਕਰੋ ਤਾਂ ਕਿ ਕੋਈ ਅੱਪਡੇਟ ਛੁੱਟ ਨਾ ਜਾਏ।",
      uri:"https://imgs.search.brave.com/V8EF-q5C_V5kZ6d2APO2ji1nJR1Idj1TRrrrfQ7NtPo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTEz/NjE4Mjg2Mi92ZWN0/b3IvbmV3LXVwZGF0/ZS1iYW5uZXItdGVt/cGxhdGUtaXNvbGF0/ZWQtb24td2hpdGUt/YmFja2dyb3VuZC12/ZWN0b3ItaWxsdXN0/cmF0aW9uLWZvci1z/dG9yZS1vbmxpbmUu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PVJDazVhMFhtTXhs/UjJXMlhraXZvUUpo/RXVRdzAtd2dPaVp2/aTJWd0ZfQ009"
    },
    {
      id: "5",
      title: "ਦੋ-ਪੜਾਅ ਪ੍ਰਮਾਣੀਕਰਨ (2FA) 🔒",
      description:
        "2FA ਨਾਲ ਤੁਹਾਡੇ ਖਾਤੇ ਦੀ ਸੁਰੱਖਿਆ ਦੋਹਰੀ ਹੋ ਜਾਂਦੀ ਹੈ। ਪਾਸਵਰਡ ਦੇ ਨਾਲ ਇਕ ਹੋਰ ਕੋਡ ਜਾਂ OTP ਲੱਗਦਾ ਹੈ। ਜਿਵੇਂ ਕਿਸੇ ਨੇ ਪਾਸਵਰਡ ਲੱਭ ਵੀ ਲਿਆ, ਪਰ ਉਸ ਕੋਡ ਤੋਂ ਬਿਨਾਂ ਖਾਤਾ ਨਹੀਂ ਖੁਲ ਸਕਦਾ। ਐਪ ਜਾਂ SMS ਤੋਂ ਆਉਣ ਵਾਲਾ ਕੋਡ ਵਰਤੋਂ। SMS ਨਾਲੋਂ Authenticator ਐਪ ਹੋਰ ਸੁਰੱਖਿਅਤ ਹੁੰਦੇ ਹਨ।",
      uri:"https://imgs.search.brave.com/JNWjLZkMcsDFkg7UrCxSeK3fyyT-1KaKBTsyQSEHwM4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMjcv/NzY5LzAxOS9zbWFs/bC8yZmEtaWNvbi10/d28tZmFjdG9yLXZl/cmlmaWNhdGlvbi1i/eS1tb2JpbGUtcGhv/bmUtdmVjdG9yLmpw/Zw"
    },
    {
      id: "6",
      title: "ਠੱਗੀ ਵਾਲੀਆਂ ਕਾਲਾਂ ਨੂੰ ਪਛਾਣੋ 📞",
      description:
        "ਠੱਗ ਬੈਂਕ ਜਾਂ ਸਰਕਾਰੀ ਕਰਮਚਾਰੀ ਬਣ ਕੇ ਕਾਲ ਕਰਕੇ ਤੁਹਾਨੂੰ ਡਰਾਉਂਦੇ ਹਨ ਕਿ 'ਤੁਰੰਤ ਖਾਤਾ ਵੈਰੀਫਾਈ ਕਰੋ, ਨਹੀਂ ਤਾਂ ਬੰਦ ਹੋ ਜਾਵੇਗਾ'। ਉਹ OTP ਜਾਂ ਰਿਮੋਟ ਐਕਸੈਸ ਲਈ ਕਹਿੰਦੇ ਹਨ। ਅਸਲੀ ਬੈਂਕ ਕਦੇ ਵੀ ਇਹ ਜਾਣਕਾਰੀ ਨਹੀਂ ਮੰਗਦਾ। ਐਸੇ ਕਾਲਾਂ ਨੂੰ ਤੁਰੰਤ ਕੱਟੋ ਅਤੇ ਸਿਰਫ਼ ਆਫੀਸ਼ਲ ਨੰਬਰ ਤੇ ਸੰਪਰਕ ਕਰੋ। ਆਪਣੇ ਪਰਿਵਾਰ ਵਿੱਚ ਵੀ ਇਹ ਜਾਣਕਾਰੀ ਸ਼ੇਅਰ ਕਰੋ।",
      uri:"https://imgs.search.brave.com/pFOLkNDUm3o-VZeg9gzCxCy6MxOqCv9DJB-mMymhRqA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTUw/MDc5NjA4NC92ZWN0/b3IvY2FydG9vbi1z/bWFydC1waG9uZS13/aXRoLWFsZXJ0LW5v/dGljZS1mbGF0LXNp/bXBsZS10cmVuZC1t/b2Rlcm4tbG9nb3R5/cGUtZ3JhcGhpYy1k/ZXNpZ24uanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPVVWc0Q0/YXFBejlsWVo1Mzh4/aXdfSlFGQnJXa2sy/M2IxaGM5UXE5Q2Yz/SUk9"
    },
  ],
};

export default cyberTopicsByLocale;
