import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F3F6F9',
        // paddingTop: 50,
        width:'100%'
    },
    chatBubbleWrapper: {
        marginBottom: 12,
    },
    userBubble: {
        alignSelf: 'flex-end',
        backgroundColor: '#A0E7E5',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 20,
        borderEndEndRadius: 0,
        maxWidth: '85%',
        marginBottom: 10,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.41,
    },
    aiBubble: {
        alignSelf: 'flex-start',
        backgroundColor: '#FFE7C1',
        padding: 14,
        borderRadius: 20,
        marginVertical: 10,
        marginHorizontal: 10,
        maxWidth: '90%',
        elevation: 2,
        borderBottomStartRadius: 0,
    },
    userText: {
        color: '#003049',
        fontSize: 16,
        lineHeight: 22,
    },
    aiText: {
        color: '#4F4F4F',
        fontSize: 16,
        lineHeight: 22,
    },
    chatImage: {
        width: 200,
        height: 200,
        borderRadius: 16,
        marginTop: 8,
        alignSelf: 'center',
    },
    inputBarWrapper: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        paddingHorizontal: 12,
        paddingBottom: 12,
        backgroundColor: 'transparent',
    },
    inputBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 10,
    },
    inputField: {
        flex: 1,
        marginHorizontal: 12,
        fontSize: 16,
        color: '#333',
    },
    sendButton: {
        backgroundColor: '#6C63FF',
        padding: 10,
        borderRadius: 50,
        marginLeft: 6,
    },
    previewContainer: {
        position: 'absolute',
        bottom: 120,
        left: 20,
        backgroundColor: '#222C3D',
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 8,
    },
    previewImage: {
        width: 180,
        height: 180,
        borderRadius: 10,
        marginRight: 10,
    },
    closePreviewBtn: {
        backgroundColor: '#E74C3C',
        padding: 6,
        borderRadius: 20,
    },
    muteBtn: {
        position: 'absolute',
        bottom: 90,
        right: 10,
        backgroundColor: '#0A66C2',
        padding: 14,
        borderRadius: 28,
        elevation: 6,
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowRadius: 6,
    },
    bottomBtn: {
        position: 'absolute',
        bottom: 150,
        right: 10,
        backgroundColor: '#0A66C2',
        padding: 14,
        borderRadius: 28,
        elevation: 6,
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowRadius: 6,
    },
    loadingDotContainer: {
        flexDirection: 'row',
        marginTop: 8,
        alignSelf: 'center',
    },
    loadingDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#6C63FF',
        marginHorizontal: 4,
        opacity: 0.6,
    },
    loaderWrapper: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 6,
    },
    loader: {
        position: 'absolute',
    },
    image: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 5,
        borderColor: '#6C63FF',
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#6C63FF',
        marginTop: 12,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        padding: 28,
        borderRadius: 20,
        alignItems: 'center',
        elevation: 12,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '600',
        marginTop: 12,
        color: '#222',
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#666',
        marginTop: 8,
        textAlign: 'center',
    },
    modalCloseBtn: {
        marginTop: 16,
        backgroundColor: '#6C63FF',
        color: '#fff',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 30,
        overflow: 'hidden',
        fontWeight: '600',
    },
});

export default styles;