import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: "#F5F5F5",
    },
    dataSourceBanner: {
        backgroundColor: "#E6F0FA",
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#E0E0E0",
    },
    dataSourceContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    dataSourceText: {
        fontSize: 12,
        marginLeft: 6,
        color: "#666",
    },
    searchContainer: {
        position: "relative",
        marginBottom: 16,
    },
    searchIcon: {
        position: "absolute",
        left: 12,
        top: 12,
        zIndex: 1,
    },
    input: {
        borderWidth: 1,
        borderColor: "#E0E0E0",
        backgroundColor: "#fff",
        padding: 12,
        paddingLeft: 40,
        borderRadius: 12,
        fontSize: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    clearButton: {
        position: "absolute",
        right: 12,
        top: 10,
    },
    resultsCount: {
        fontSize: 14,
        color: "#666",
        marginBottom: 12,
    },
    card: {
        backgroundColor: "#fff",
        padding: 16,
        marginBottom: 16,
        borderRadius: 12,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    cardHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    appIcon: {
        backgroundColor: "#007AFF",
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 10,
    },
    socialIcon: {
        backgroundColor: "#34C759",
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 10,
    },
    title: {
        fontSize: 18,
        fontWeight: "600",
        color: "#222",
        flex: 1,
    },
    detailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    detailText: {
        marginLeft: 8,
        color: "#444",
        fontSize: 14,
    },
    linkContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginTop: 12,
    },
    linkButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#007AFF",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        marginRight: 8,
        marginBottom: 8,
    },
    linkButtonText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "500",
        marginLeft: 4,
    },
    socialButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 8,
        marginBottom: 8,
    },
    emptyState: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 60,
    },
    emptyStateText: {
        fontSize: 18,
        fontWeight: "600",
        color: "#666",
        marginTop: 16,
        marginBottom: 8,
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: "#999",
        textAlign: "center",
        paddingHorizontal: 40,
    },
    link: {
        color: "#007AFF",
        fontWeight: "500",
    },
});